### ISSUE TITLE
Update peer dependency to @testing-library/dom 9.x

### ISSUE THREAD

**Issue by stefanroeck** [domasx2/testing-library-selector#6]
- **I'm submitting a ...**
  [x] feature request

- **Summary**
Currently, `"@testing-library/dom": "^8.2.0"` does not allow version 9.x. Release Notes: https://github.com/testing-library/dom-testing-library/releases

**Comment by domasx2** [comment]
released 0.3.1 with updated deps!

**Comment by SerhiyVolochii-cobalt** [comment]
Thanks!
